### ISSUE TITLE
关于IIS_backdoor有几个疑问想请教

### ISSUE THREAD

**Issue by wangzai125** [c1y2m3/misc#1]
楼主你好，看了你写的文章<探索基于HTTP.SYS实现权限维持 >之后，我想动手验证一下端口复用的效果，发现无论是微软官方给出的示例代码，还是你的 IIS_backdoor.cpp 文件，我都没能编译成功，google很久之后也没有解决。我用的是 vs code + mingw-w64编译器，请问是我的编译环境有问题吗？能否介绍一下你的编译环境呢？
以下是我的报错信息，供您参考
<pre><code>
HTTPServer_eg.cpp: In function 'char* ExeCmd(WCHAR*)':
HTTPServer_eg.cpp:62:35: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   return ("[!] CreatePipe failed.");
                                   ^
HTTPServer_eg.cpp:78:38: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   return ("[!] CreateProcess failed.");
                                      ^
HTTPServer_eg.cpp:85:7: warning: address of local variable 'strText' returned [-Wreturn-local-addr]
  char strText[32768] = { 0 };
       ^~~~~~~
HTTPServer_eg.cpp: In function 'char* TextToHtml(char*)':
HTTPServer_eg.cpp:103:20: warning: comparison of integer expressions of different signedness: 'int' and 'size_t' {aka 'long long unsigned int'} [-Wsign-compare]
  for (int i = 0; i < strlen(String1); i++)
                  ~~^~~~~~~~~~~~~~~~~
HTTPServer_eg.cpp: In function 'DWORD DoReceiveRequests(HANDLE)':
HTTPServer_eg.cpp:367:7: warning: ISO C++ forbids converting a string constant to 'PSTR' {aka 'char*'} [-Wwrite-strings]
       );
       ^
HTTPServer_eg.cpp:367:7: warning: ISO C++ forbids converting a string constant to 'PSTR' {aka 'char*'} [-Wwrite-strings]
HTTPServer_eg.cpp:390:7: warning: ISO C++ forbids converting a string constant to 'PSTR' {aka 'char*'} [-Wwrite-strings]
       );
       ^
HTTPServer_eg.cpp:407:6: warning: ISO C++ forbids converting a string constant to 'PSTR' {aka 'char*'} [-Wwrite-strings]
      );
      ^
HTTPServer_eg.cpp:407:6: warning: ISO C++ forbids converting a string constant to 'PSTR' {aka 'char*'} [-Wwrite-strings]
HTTPServer_eg.cpp:422:6: warning: ISO C++ forbids converting a string constant to 'PSTR' {aka 'char*'} [-Wwrite-strings]
      );
      ^
C:\Users\WIN10\AppData\Local\Temp\ccHqzYbT.o: In function `SendHttpResponse(void*, _HTTP_REQUEST_V2*, unsigned short, char*, char*)':
C:\Users\WIN10\source_code/HTTPServer_eg.cpp:548: undefined reference to `__imp_HttpSendHttpResponse'
C:\Users\WIN10\AppData\Local\Temp\ccHqzYbT.o: In function `SendHttpPostResponse(void*, _HTTP_REQUEST_V2*)':
C:\Users\WIN10\source_code/HTTPServer_eg.cpp:678: undefined reference to `__imp_HttpReceiveRequestEntityBody'
C:\Users\WIN10\source_code/HTTPServer_eg.cpp:755: undefined reference to `__imp_HttpSendHttpResponse'
C:\Users\WIN10\source_code/HTTPServer_eg.cpp:832: undefined reference to `__imp_HttpSendHttpResponse'
C:\Users\WIN10\source_code/HTTPServer_eg.cpp:792: undefined reference to `__imp_HttpSendResponseEntityBody'
C:\Users\WIN10\AppData\Local\Temp\ccHqzYbT.o: In function `DoReceiveRequests(void*)':
C:\Users\WIN10\source_code/HTTPServer_eg.cpp:332: undefined reference to `__imp_HttpReceiveHttpRequest'
C:\Users\WIN10\AppData\Local\Temp\ccHqzYbT.o: In function `wmain':
C:\Users\WIN10\source_code/HTTPServer_eg.cpp:199: undefined reference to `__imp_HttpInitialize'
C:\Users\WIN10\source_code/HTTPServer_eg.cpp:214: undefined reference to `__imp_HttpCreateHttpHandle'
C:\Users\WIN10\source_code/HTTPServer_eg.cpp:219: undefined reference to `__imp_HttpAddUrl'
C:\Users\WIN10\source_code/HTTPServer_eg.cpp:264: undefined reference to `__imp_HttpRemoveUrl'
C:\Users\WIN10\source_code/HTTPServer_eg.cpp:283: undefined reference to `__imp_HttpTerminate'
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-crt0_c.o):crt0_c.c:(.text.startup+0x2e): undefined reference to `WinMain'
collect2.exe: error: ld returned 1 exit status
PS C:\Users\WIN10\source_code>
</code></pre>

**Comment by c1y2m3** [comment]
之前的代码比较久了，已上传sln工程文件，直接编译即可使用。
